codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        informational: true
        branches:
          - main
    patch:
      default:
        target: 80%
        threshold: 1%
        informational: true

flags:
  unit-tests:
    carryforward: true
  integration-tests:
    carryforward: true
  e2e-tests:
    carryforward: true

ignore:
  - "tests/"
  - "venv/"
  - "__pycache__/"
  - "*.pyc"
  - ".github/"
  - "docs/"
  - "k8s/"
  - "testdata/"

comment:
  layout: "reach,diff,flags,files,footer"
  require_changes: true
